pearson:
	@python3 myrecsys.py hw2.input.tab hw2.input_actual.tab user-pearson

cosine:
	@python3 myrecsys.py hw2.input.tab hw2.input_actual.tab item-cosine

all:
	@python3 myrecsys.py hw2.input.tab hw2.input_actual.tab average
	@echo
	@python3 myrecsys.py hw2.input.tab hw2.input_actual.tab user-euclidean
	@echo
	@python3 myrecsys.py hw2.input.tab hw2.input_actual.tab user-pearson
	@echo
	@python3 myrecsys.py hw2.input.tab hw2.input_actual.tab item-cosine
